### ISSUE TITLE
FileNotFoundError:  [Errno 2] No such file or directory: 'checkpoint/regular_c109_n32/conv2.yaml'

### ISSUE THREAD

**Issue by leidaguo** [JiaminRen/RandWireNN#9]
Hello, I have an error message, I don't know if this file is missing. I hope to get your reply. Thank you。
FileNotFoundError:  [Errno 2] No such file or directory: 'checkpoint/regular_c109_n32/conv2.yaml'

**Comment by JiaminRen** [comment]
Can you give more error logs?

**Comment by leidaguo** [comment]
Enabled distributed training.
Enabled distributed training.
Enabled distributed training.
Enabled distributed training.
Enabled distributed training.
Enabled distributed training.
Enabled distributed training.
Enabled distributed training.
Traceback (most recent call last):
  File "train.py", line 305, in <module>
    main()
  File "train.py", line 57, in main
    model = CNN(args)
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/model.py", line 114, in __init__
    save_graph(graph, os.path.join(args.model_dir, 'conv2.yaml'))
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/utils.py", line 33, in save_graph
    nx.write_yaml(graph, path)
  File "<decorator-gen-430>", line 2, in write_yaml
  File "/raid/home/leidaguo/anaconda3/lib/python3.6/site-packages/networkx/utils/decorators.py", line 205, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/regular_c109_n32/conv2.yaml'
Traceback (most recent call last):
  File "train.py", line 305, in <module>
    main()
  File "train.py", line 57, in main
    model = CNN(args)
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/model.py", line 114, in __init__
    save_graph(graph, os.path.join(args.model_dir, 'conv2.yaml'))
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/utils.py", line 33, in save_graph
    nx.write_yaml(graph, path)
  File "<decorator-gen-430>", line 2, in write_yaml
  File "/raid/home/leidaguo/anaconda3/lib/python3.6/site-packages/networkx/utils/decorators.py", line 205, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/regular_c109_n32/conv2.yaml'
Traceback (most recent call last):
  File "train.py", line 305, in <module>
    main()
  File "train.py", line 57, in main
    model = CNN(args)
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/model.py", line 114, in __init__
    save_graph(graph, os.path.join(args.model_dir, 'conv2.yaml'))
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/utils.py", line 33, in save_graph
    nx.write_yaml(graph, path)
  File "<decorator-gen-430>", line 2, in write_yaml
  File "/raid/home/leidaguo/anaconda3/lib/python3.6/site-packages/networkx/utils/decorators.py", line 205, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/regular_c109_n32/conv2.yaml'
Traceback (most recent call last):
  File "train.py", line 305, in <module>
    main()
  File "train.py", line 57, in main
    model = CNN(args)
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/model.py", line 114, in __init__
    save_graph(graph, os.path.join(args.model_dir, 'conv2.yaml'))
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/utils.py", line 33, in save_graph
    nx.write_yaml(graph, path)
  File "<decorator-gen-430>", line 2, in write_yaml
  File "/raid/home/leidaguo/anaconda3/lib/python3.6/site-packages/networkx/utils/decorators.py", line 205, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/regular_c109_n32/conv2.yaml'
Traceback (most recent call last):
  File "train.py", line 305, in <module>
    main()
  File "train.py", line 57, in main
    model = CNN(args)
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/model.py", line 114, in __init__
    save_graph(graph, os.path.join(args.model_dir, 'conv2.yaml'))
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/utils.py", line 33, in save_graph
    nx.write_yaml(graph, path)
  File "<decorator-gen-430>", line 2, in write_yaml
  File "/raid/home/leidaguo/anaconda3/lib/python3.6/site-packages/networkx/utils/decorators.py", line 205, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/regular_c109_n32/conv2.yaml'
Traceback (most recent call last):
  File "train.py", line 305, in <module>
    main()
  File "train.py", line 57, in main
    model = CNN(args)
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/model.py", line 114, in __init__
    save_graph(graph, os.path.join(args.model_dir, 'conv2.yaml'))
  File "/raid/home/leidaguo/nas/jiaminren/RandWireNN/utils.py", line 33, in save_graph
    nx.write_yaml(graph, path)
  File "<decorator-gen-430>", line 2, in write_yaml
  File "/raid/home/leidaguo/anaconda3/lib/python3.6/site-packages/networkx/utils/decorators.py", line 205, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/regular_c109_n32/conv2.yaml'

**Comment by JiaminRen** [comment]
Check  if the [train.py ](https://github.com/JiaminRen/RandWireNN/blob/master/train.py#L52) executed successfully. And is the path(args.model_dir) existed.

**Comment by JiaminRen** [comment]
check
